version: "3"
services:
  db:
    image: mysql
    container_name: mysql_web
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PW}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "9906:3306"
    volumes:
      - ./data:/var/lib/mysql
  web:
    build:
      context: .
      dockerfile: "Dockerfile"
    container_name: php_web
    ports:
      - "8000:80"